# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_pinned',
        ),
        migrations.AddField(
            model_name='poststatistics',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='statsys.Post', verbose_name='пост'),
            preserve_default=False,
        ),
    ]
