# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsys', '0002_auto_20170412_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststatistics',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
