# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsys', '0003_auto_20170412_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststatistics',
            name='date',
            field=models.IntegerField(verbose_name='Дата публикации в unixtime'),
        ),
    ]
